### PR TITLE
Added simple drawing functions

### PR DESCRIPTION
**Pull request by wuehr1999**
Hi @generationmake,

I took Your display library and added the following methods for drawing simple shapes based on a canvas:
* setPixel(int x, int y, bool value);
* drawLine(int x0, int y0, int x1, int y1);
* drawCircle(int x0, int y0, int r, bool fill); 
* drawRect(int x0, int y0, int width, int height, bool fill);
* drawCross(int x0, int y0, int width, int height);

I also added an Example3_DrawingFunctions to test all of them ;-)

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @wuehr1999 
these are very nice functions.
But I think it would be better if we make the canvas more flexible and not fixed to 128x64 pixels. This would allow to use it also for the smaller displays. Or on bigger displays to use only a part of it. An init function should dynamically allocate the memory for the canvas and store its actual size in the class.

**Comment by wuehr1999** [comment]
Hi @generationmake,

I added a alternative begin method:
* void begin (byte p_cs, byte p_si, byte p_clk, byte p_a0, byte p_res, byte type, byte canvasSizeX, byte canvasSizeY, byte canvasUpperLeftX, byte canvasUpperLeftY);

Here the size of the canvas and it's position on the screen can be defined, so it is possible to use a specific part on the display.
I think this is what You wanted?

**Comment by generationmake** [comment]
Yes, this is somehow what I expected. I think I will do some more tests and see how it works.

**Comment by generationmake** [comment]
Hi @wuehr1999 
I have tested it and it seems to work.
but when you set canvasSizeY to a different value in the createcanvas function it does not work and the output gets corrupted.
Could you check this?

**Comment by wuehr1999** [comment]
Hi @generationmake, 
i found the problem (fitting of canvasSizeY in the 8-bit pages) and fixed it.
Could You please try if it is working for You now?

**Comment by generationmake** [comment]
library works for now. I will merge.

**Review by generationmake — APPROVED** [review]

**Pull request merged**
